### ISSUE TITLE
save file extension when $file_name = true

### ISSUE THREAD

**Issue by andreipan** [jbroadway/urlify#43]
`\URLify::filter('abcdefghi.jpg', 6, 'en', true);
// returns abcdef`

It would be good to save extension of the file name so to have the result 'abcdef.jpg' in this case.

**Comment by jbroadway** [comment]
If you make the character limit longer, it doesn't strip out the file extension if there are enough characters remaining, for example:

```php
\URLify::filter('abcdefghi.jpg', 60, 'en', true); // returns abcdefghi.jpg
```

Otherwise, if you need it shorter but want to keep the extension your best bet would be to capture the extension via `$ext = pathinfo ($path, PATHINFO_EXTENSION);` then append it back to the result.
