### ISSUE TITLE
Missing A char

### ISSUE THREAD

**Issue by marlenesco** [jbroadway/urlify#52]
Hi, I found a strange bug, look at the below code (local ENV: php 5.6 on mac os, dev-prod ENV: php 5.6 on ubuntu 16):

 - `var_dump(\URLify::filter('Text sample A'));`       //    text-sample 
 - `var_dump(\URLify::filter('Text sample B'));`       //   text-sample-b
 - `var_dump(\URLify::filter('Text sample AA'));`     //  text-sample-aa

Where is, in the first var_dump, the last "a" char?

Is this package still maintained?

**Comment by lux** [comment]
The 'a' is getting stripped out because of the `$remove_list` property, which has a list of words to strip out:

https://github.com/jbroadway/urlify/blob/master/URLify.php#L148-L153

You can adjust it by providing your own list, for example if you want no words stripped out you could do:

```php
URLify::$remove_list = [];
```

Hope that helps! And yes, this package is still maintained 😄

**Comment by marlenesco** [comment]
Thanks for detailed explanation @lux
Have a nice day
