### ISSUE TITLE
Not compatable with Laravel 9

### ISSUE THREAD

**Issue by emedchill** [jbroadway/urlify#69]
Since Laravel 9 is requiring `voku/portable-ascii:^2.0` and this repo is requiring `voku/portable-ascii:^1.4` it causes a conflict when trying to update composer.

**Comment by lux** [comment]
I've started a branch to fix this but looks like the update breaks some test fixtures so I'll have to go through and fix those before merging.

**Comment by madman-81** [comment]
@lux, do you have an update for us? Really looking forward to Laravel 9 support! Anything we can do to help?

**Comment by madman-81** [comment]
@lux, I'm not familiar with the portable-ascii package, but from what I see in the code and the change log, they changed the way Russian characters are converted by replacing "GOST 7.79-2000(B)" with "Passport (2013), ICAO", amongst others. This also has an effect on other, similar, languages like Bulgarian. Not sure if this is expected behaviour, but since there is no 'source language' specified when strings are converted, this might indeed happen (that Russian characters are used when a Bulgarian sentence is converted). 

If you look at this Bulgarian sentence "Bulgarian: Жълтата дюля беше щастлива, че пухът, който цъфна, замръзна като гьон", it was converted to "bulgarian-zltata-dyulya-bese-shhastliva-ce-puxt-koito-cfna-zamrzna-kato-gyon" with the 1.6 version, but with version 2.0 it would become "bulgarian-zieltata-diulia-bese-shhastliva-ce-puxiet-koito-ciefna-zamriezna-kato-gyon".

In a bit more detail: the "ъ" character is now converted to "ie" (used to be "l"). This matches with the GOST/Passport change:
[src/voku/helper/data/ascii_by_languages.php](https://github.com/voku/portable-ascii/compare/1.6.1...2.0.1#diff-8655140c89ed1c25f842ff68215ee880b19c77990e9bee3ad0101e91b9b5f2c6) on line 1223 in the new version (the link isn't fully working some how).

So the first question that needs to be answered is: Is it OK that the new version of `voku/portable-ascii` will change the output that is generated?

**Comment by madman-81** [comment]
@lux Any thoughts on this?

**Comment by jbroadway** [comment]
@madman-81 I think it's okay for the output to change since the best practice would be to generate the slug one time and store it somewhere instead of generating it fresh for every request. That wouldn't be great for performance reasons. So I think we're safe to update things to match the underlying voku/portable-ascii changes.

**Comment by madman-81** [comment]
@lux, I've updated the expected output. See PR #71
